---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_check.stat.exists

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name:
      - hammerspoon
      - xquartz
      - alfred
      - little-snitch
      - karabiner-elements
      - ubersicht
      - firefox
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name:
      - bash
      - bash-completion@2
      - gnu-sed
      - go
      - openssl@3
      - ssh-copy-id
      - terminal-notifier
      - wireguard-go
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
